stages:
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: python:3.9

before_script:
  - pip install hatch hatch-vcs

test:
  stage: test
  script:
    - hatch test

coverage:
  stage: test
  script:
    - hatch test --cover
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - hatch build
    - mkdir -p artifacts
    - cp dist/* artifacts/
  artifacts:
    paths:
    - artifacts/
  after_script:
    - echo "Deployment finished."
    - rm -rf dist
    - rm -rf artifacts
  only:
  - tags