stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: python:3.9

before_script:
  - pip install hatch hatch-vcs

build:
  stage: build
  script:
    - echo "my_arithmetic-dehou-yasmine deployment on develop servers"
    - hatch build
    - ls -l dist/
    - mkdir -p artifacts
    - cp -r dist/ artifacts/
    - rm -rf dist/
  artifacts:
    paths:
      - artifacts/
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

test:
  stage: test
  script:
    - hatch test

coverage:
  stage: test
  script:
    - hatch test --cover
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:
  stage: deploy
  script:
    - echo "my_arithmetic-dehou-yasmine deployment on stable servers
    - hatch build
    - ls -l dist/
    - mkdir -p artifacts
    - cp -r dist/ artifacts/
    - rm -rf dist/
  artifacts:
    paths:
    - artifacts/
  only:
  - tags

sync-with-github:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote add github $REMOTE_REPOSITORY_URL
    - git checkout master
    - git pull origin master
    - git pull github master
    - git status
    - git push https://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master