stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: python:3.9

before_script:
  - pip install hatch hatch-vcs

build:
  stage: build
  script:
    - echo "my_arithmetic-dehou-yasmine deployment on develop servers"
    - hatch build
    - ls -l dist/
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

test:
  stage: test
  script:
    - hatch test

coverage:
  stage: test
  script:
    - hatch test --cover
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:
  stage: deploy
  script:
    - echo "my_arithmetic-dehou-yasmine deployment on stable servers
    - hatch build
    - ls -l dist/
  artifacts:
    paths:
    - dist/
  only:
  - tags
