stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: python:3.9

before_script:
  - pip install hatch hatch-vcs

test:
  stage: test
  script:
    - hatch test

test_coverage:
  stage: test
  script:
    - hatch test --cover
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml