name: Test and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install ourself
        run: |
          uv pip install --system -e .

#      - name: Run static analysis
#        run: hatch fmt --check

#      - name: Check types
#        run: hatch run types:check

      - name: Run tests
        run: hatch test --cover-quiet --randomize --parallel --retries 5 --retry-delay 3

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: coverage
          path: .coverage

  coverage:
    name: Report coverage
    runs-on: ubuntu-latest
    needs:
    - test

    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Trigger build for auto-generated files
      run: hatch build --hooks-only

    - name: Download coverage data
      uses: actions/download-artifact@v4
      with:
        pattern: coverage
        merge-multiple: true

#    - name: Combine coverage data
#      run: hatch run coverage:combine

    - name: Export coverage reports
      run: |
        hatch run coverage:report-xml
        hatch run coverage:report-uncovered-html

    - name: Upload uncovered HTML report
      uses: actions/upload-artifact@v4
      with:
        name: uncovered-html-report
        path: htmlcov